### ISSUE TITLE
No distinction between explicitly and implicitly assigned enum values in HTML docs.

### ISSUE THREAD

**Issue by MisterGC** [ndsev/zserio#481] opened 2023-02-16 14:32 UTC
zserio generated HTML docs contain enum values also for auto-generated/implicitly assigned enum values. This is misleading and can be confusing when talking about the enum values, because it creates the impression that schema authors have explicitly decided to assign value. But exactly the opposite is the case, schema authors use this feature with "I don't care about the actual value, but assume that zserio keeps it stable as long as the position of the  element doesn't change" in mind.

Example:
``` C
enum uint8 Colors
{
  RED,
  GREEN,
  BLUE
};
```
Generate the HTML docu and the result will contain `RED = 0, GREEN = 1 and BLUE = 2` as if the author did that explicitly.

**Suggestion**: Omit these values in this case, the author intended that users should not care about the actual value when studying the schema. 

In case there are users who really need the value the explicit assignment could be commented `// = 1, assigned implicitly'

**Comment by Mi-La** [comment] 2023-02-16 15:07
Duplicate of #468?

**Closed** 2023-02-17 06:25 UTC
Labels: doc

**Comment by MisterGC** [comment] 2023-02-17 09:07
yes, sorry - will extend the original issue and add my comments there
